apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.configMap }}
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
data:
  db-create.sql: {{ toYaml .Values.postgres.sqlScript | indent 2 }}