apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.server.configMap }}
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
data:
  # note homeserver.yaml is mounted as a secret as it features db creds, no suitable for a configMap
  neukolln-matrix-dev.com.log.config: |
    version: 1
    formatters:
      precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
    loggers:
        synapse.storage.SQL:
            # beware: increasing this to DEBUG will make synapse log sensitive
            # information such as access tokens.
            level: INFO
    root:
        level: INFO
        handlers: [console]
    disable_existing_loggers: false
  neukolln-matrix-dev.com.signing.key: ed25519 a_nBnV g9Ia1Nt0ip8N22QRr/KV5fMpBIMpzJQBJvkTxn+jBV4