apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.server.ingress.name }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        location /.well-known/matrix/server {
          return 200 '{"m.server": "neukolln-matrix-dev.com:443"}';
          add_header Content-Type application/json;
        }
spec:
  tls:
  - hosts:
    - {{ .Values.server.host }}
    secretName: synapse-tls
  rules:
    - host: {{ .Values.server.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Values.server.service.name }}
                port:
                  number: {{ .Values.server.service.port }}